### ISSUE TITLE
failed to install this plugin

### ISSUE THREAD

**Issue by asciel** [GerritCodeReview/plugins_code-owners#1]
Hi, I have downloaded this plugin using " wget  https://gerrit-ci.gerritforge.com/job/plugin-code-owners-bazel-stable-3.4/lastSuccessfulBuild/artifact/bazel-bin/plugins/code-owners/code-owners.jar " and move the code-owners.jar into the /plugins dir, and restart my gerrit, but it doesn't work and I can't find this plugin in the Plugins List  whose path is /admin/plugins. Hope for help, thanks.

- my env is  gerrit-2.14.16, jdk8

**Comment by davido** [comment]
Please, use this mail list for [questions](https://groups.google.com/g/repo-discuss). 

> plugin-code-owners-bazel-stable-3.4

is incompatible with gerrit 2.14.
